name: ci
on: [push, pull_request]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps (if present)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Quick smoke
        run: python - <<'PY'
print('OK: python workflow')
PY
